/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/dev/auth/quick-login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['quickLogin']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/dev/auth/revoke-all': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['revokeAllSessions']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/dev/auth/revoke-user': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['revokeUserSessions']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/dev/monzo/backfill': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['triggerBackfill']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/dev/monzo/ingest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['triggerIngest']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/dev/monzo/reset-backfill/{accountId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['resetBackfill']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @deprecated */
    get: operations['health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health/live': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @deprecated */
    get: operations['liveness']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/health/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @deprecated */
    get: operations['readiness']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listAccounts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/accounts/{id}/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getSummary']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['refresh']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/verify': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['verify']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/monzo/callback': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['handleCallback']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/monzo/connect': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['initiateOAuth']
    put?: never
    post: operations['initiateOAuthJson']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/monzo/connections': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['listConnections']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/monzo/connections/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getConnection']
    put?: never
    post?: never
    delete: operations['disconnectConnection']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/monzo/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getStatus']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/monzo/sync': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['syncNow']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/monzo/sync/progress': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['getSyncProgress']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/transactions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['list']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    AccountProgress: {
      accountId?: string
      currentWindowDate?: string
      description?: string
      /** Format: int32 */
      progressPercent?: number
      status?: string
      /** Format: int64 */
      transactionCount?: number
    }
    AccountResponse: {
      /** @enum {string} */
      accountType?: 'CURRENT' | 'SAVINGS' | 'CREDIT_CARD' | 'OTHER'
      archived?: boolean
      /** Format: date-time */
      balanceAsOf?: string
      /** Format: int64 */
      balanceMinorUnits?: number
      /** Format: int64 */
      creditLimitMinorUnits?: number
      currency?: string
      displayName?: string
      /** Format: int32 */
      displayOrder?: number
      /** Format: uuid */
      id?: string
      institutionName?: string
      /** @enum {string} */
      provider?: 'MONZO' | 'TRUELAYER'
    }
    AccountSummaryResponse: {
      /** Format: uuid */
      accountId?: string
      monthToDate?: components['schemas']['WindowSums']
      thisWeek?: components['schemas']['WindowSums']
      today?: components['schemas']['WindowSums']
      zone?: string
    }
    ApiResponseAccountSummaryResponse: {
      data?: components['schemas']['AccountSummaryResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseAuthResponse: {
      data?: components['schemas']['AuthResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseDevLoginResponse: {
      data?: components['schemas']['DevLoginResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseHealthResponse: {
      data?: components['schemas']['HealthResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseListAccountResponse: {
      data?: components['schemas']['AccountResponse'][]
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseListMonzoConnectionResponse: {
      data?: components['schemas']['MonzoConnectionResponse'][]
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseMonzoConnectInitResponse: {
      data?: components['schemas']['MonzoConnectInitResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseMonzoConnectionResponse: {
      data?: components['schemas']['MonzoConnectionResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseMonzoStatusResponse: {
      data?: components['schemas']['MonzoStatusResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseMonzoSyncProgressResponse: {
      data?: components['schemas']['MonzoSyncProgressResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponsePageResponseTransactionResponse: {
      data?: components['schemas']['PageResponseTransactionResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseReadinessResponse: {
      data?: components['schemas']['ReadinessResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseRevokeResponse: {
      data?: components['schemas']['RevokeResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseUserResponse: {
      data?: components['schemas']['UserResponse']
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApiResponseVoid: {
      data?: Record<string, never>
      success?: boolean
      /** Format: date-time */
      timestamp?: string
    }
    ApplicationContext: {
      applicationName?: string
      autowireCapableBeanFactory?: components['schemas']['AutowireCapableBeanFactory']
      /** Format: int32 */
      beanDefinitionCount?: number
      beanDefinitionNames?: string[]
      classLoader?: {
        defaultAssertionStatus?: boolean
        definedPackages?: {
          annotations?: Record<string, never>[]
          declaredAnnotations?: Record<string, never>[]
          implementationTitle?: string
          implementationVendor?: string
          implementationVersion?: string
          name?: string
          sealed?: boolean
          specificationTitle?: string
          specificationVendor?: string
          specificationVersion?: string
        }[]
        name?: string
        registeredAsParallelCapable?: boolean
        unnamedModule?: {
          annotations?: Record<string, never>[]
          declaredAnnotations?: Record<string, never>[]
          descriptor?: {
            automatic?: boolean
            open?: boolean
          }
          layer?: Record<string, never>
          name?: string
          named?: boolean
          nativeAccessEnabled?: boolean
          packages?: string[]
        }
      }
      displayName?: string
      environment?: components['schemas']['Environment']
      id?: string
      parent?: components['schemas']['ApplicationContext']
      parentBeanFactory?: components['schemas']['BeanFactory']
      /** Format: int64 */
      startupDate?: number
    }
    AuthResponse: {
      accessToken?: string
      email?: string
      message?: string
      refreshToken?: string
    }
    AutowireCapableBeanFactory: Record<string, never>
    BeanFactory: Record<string, never>
    DatabaseHealth: {
      error?: string
      status?: string
    }
    DefaultHttpStatusCode: components['schemas']['HttpStatusCode']
    DevLoginRequest: {
      email?: string
    }
    DevLoginResponse: {
      accessToken?: string
      email?: string
      hint?: string
      refreshToken?: string
      userId?: string
    }
    Environment: {
      activeProfiles?: string[]
      defaultProfiles?: string[]
    }
    FilterRegistration: {
      className?: string
      initParameters?: {
        [key: string]: string
      }
      name?: string
      servletNameMappings?: string[]
      urlPatternMappings?: string[]
    }
    HealthResponse: {
      profile?: string
      status?: string
      timestamp?: string
    }
    /** @enum {unknown} */
    HttpStatus:
      | '100 CONTINUE'
      | '101 SWITCHING_PROTOCOLS'
      | '102 PROCESSING'
      | '103 EARLY_HINTS'
      | '200 OK'
      | '201 CREATED'
      | '202 ACCEPTED'
      | '203 NON_AUTHORITATIVE_INFORMATION'
      | '204 NO_CONTENT'
      | '205 RESET_CONTENT'
      | '206 PARTIAL_CONTENT'
      | '207 MULTI_STATUS'
      | '208 ALREADY_REPORTED'
      | '226 IM_USED'
      | '300 MULTIPLE_CHOICES'
      | '301 MOVED_PERMANENTLY'
      | '302 FOUND'
      | '303 SEE_OTHER'
      | '304 NOT_MODIFIED'
      | '307 TEMPORARY_REDIRECT'
      | '308 PERMANENT_REDIRECT'
      | '400 BAD_REQUEST'
      | '401 UNAUTHORIZED'
      | '402 PAYMENT_REQUIRED'
      | '403 FORBIDDEN'
      | '404 NOT_FOUND'
      | '405 METHOD_NOT_ALLOWED'
      | '406 NOT_ACCEPTABLE'
      | '407 PROXY_AUTHENTICATION_REQUIRED'
      | '408 REQUEST_TIMEOUT'
      | '409 CONFLICT'
      | '410 GONE'
      | '411 LENGTH_REQUIRED'
      | '412 PRECONDITION_FAILED'
      | '413 CONTENT_TOO_LARGE'
      | '413 PAYLOAD_TOO_LARGE'
      | '414 URI_TOO_LONG'
      | '415 UNSUPPORTED_MEDIA_TYPE'
      | '416 REQUESTED_RANGE_NOT_SATISFIABLE'
      | '417 EXPECTATION_FAILED'
      | '418 I_AM_A_TEAPOT'
      | '421 MISDIRECTED_REQUEST'
      | '422 UNPROCESSABLE_CONTENT'
      | '422 UNPROCESSABLE_ENTITY'
      | '423 LOCKED'
      | '424 FAILED_DEPENDENCY'
      | '425 TOO_EARLY'
      | '426 UPGRADE_REQUIRED'
      | '428 PRECONDITION_REQUIRED'
      | '429 TOO_MANY_REQUESTS'
      | '431 REQUEST_HEADER_FIELDS_TOO_LARGE'
      | '451 UNAVAILABLE_FOR_LEGAL_REASONS'
      | '500 INTERNAL_SERVER_ERROR'
      | '501 NOT_IMPLEMENTED'
      | '502 BAD_GATEWAY'
      | '503 SERVICE_UNAVAILABLE'
      | '504 GATEWAY_TIMEOUT'
      | '505 HTTP_VERSION_NOT_SUPPORTED'
      | '506 VARIANT_ALSO_NEGOTIATES'
      | '507 INSUFFICIENT_STORAGE'
      | '508 LOOP_DETECTED'
      | '509 BANDWIDTH_LIMIT_EXCEEDED'
      | '510 NOT_EXTENDED'
      | '511 NETWORK_AUTHENTICATION_REQUIRED'
    HttpStatusCode: {
      error?: boolean
      is1xxInformational?: boolean
      is2xxSuccessful?: boolean
      is3xxRedirection?: boolean
      is4xxClientError?: boolean
      is5xxServerError?: boolean
    }
    JspConfigDescriptor: {
      jspPropertyGroups?: components['schemas']['JspPropertyGroupDescriptor'][]
      taglibs?: components['schemas']['TaglibDescriptor'][]
    }
    JspPropertyGroupDescriptor: {
      buffer?: string
      defaultContentType?: string
      deferredSyntaxAllowedAsLiteral?: string
      elIgnored?: string
      errorOnELNotFound?: string
      errorOnUndeclaredNamespace?: string
      includeCodas?: string[]
      includePreludes?: string[]
      isXml?: string
      pageEncoding?: string
      scriptingInvalid?: string
      trimDirectiveWhitespaces?: string
      urlPatterns?: string[]
    }
    LoginRequest: {
      email?: string
    }
    MonzoConnectInitResponse: {
      authorizationUrl?: string
      message?: string
    }
    MonzoConnectionResponse: {
      /** Format: date-time */
      connectedAt?: string
      /** Format: date-time */
      expiresAt?: string
      /** Format: uuid */
      id?: string
      isActive?: boolean
      isTokenExpired?: boolean
      monzoUserId?: string
    }
    MonzoStatusResponse: {
      /** @enum {string} */
      backfillStatus?: 'NOT_STARTED' | 'IN_PROGRESS' | 'NEEDS_REAUTH' | 'COMPLETED'
      connected?: boolean
      /** Format: int64 */
      connectionCount?: number
      /** @enum {string} */
      tokenStatus?: 'ACTIVE' | 'EXPIRING_SOON' | 'RECONNECT_REQUIRED'
    }
    MonzoSyncProgressResponse: {
      accounts?: components['schemas']['AccountProgress'][]
    }
    PageResponseTransactionResponse: {
      items?: components['schemas']['TransactionResponse'][]
      /** Format: int32 */
      page?: number
      /** Format: int32 */
      size?: number
      /** Format: int64 */
      totalElements?: number
      /** Format: int32 */
      totalPages?: number
    }
    ReadinessResponse: {
      database?: components['schemas']['DatabaseHealth']
      profile?: string
      status?: string
      timestamp?: string
    }
    RedirectView: {
      applicationContext?: components['schemas']['ApplicationContext']
      attributes?: {
        [key: string]: string
      }
      attributesCSV?: string
      attributesMap?: {
        [key: string]: Record<string, never>
      }
      beanName?: string
      contentType?: string
      contextRelative?: boolean
      encodingScheme?: string
      expandUriTemplateVariables?: boolean
      exposeContextBeansAsAttributes?: boolean
      exposeModelAttributes?: boolean
      exposePathVariables?: boolean
      exposedContextBeanNames?: string[]
      hosts?: string[]
      http10Compatible?: boolean
      propagateQueryParams?: boolean
      propagateQueryProperties?: boolean
      redirectView?: boolean
      requestContextAttribute?: string
      servletContext?: components['schemas']['ServletContext']
      staticAttributes?: {
        [key: string]: Record<string, never>
      }
      statusCode?:
        components['schemas']['DefaultHttpStatusCode'] | components['schemas']['HttpStatus']
      url?: string
    }
    RefreshRequest: {
      refreshToken?: string
    }
    RevokeResponse: {
      message?: string
      /** Format: int32 */
      sessionsRevoked?: number
    }
    ServletContext: {
      attributeNames?: Record<string, never>
      classLoader?: {
        defaultAssertionStatus?: boolean
        definedPackages?: {
          annotations?: Record<string, never>[]
          declaredAnnotations?: Record<string, never>[]
          implementationTitle?: string
          implementationVendor?: string
          implementationVersion?: string
          name?: string
          sealed?: boolean
          specificationTitle?: string
          specificationVendor?: string
          specificationVersion?: string
        }[]
        name?: string
        registeredAsParallelCapable?: boolean
        unnamedModule?: {
          annotations?: Record<string, never>[]
          declaredAnnotations?: Record<string, never>[]
          descriptor?: {
            automatic?: boolean
            open?: boolean
          }
          layer?: Record<string, never>
          name?: string
          named?: boolean
          nativeAccessEnabled?: boolean
          packages?: string[]
        }
      }
      contextPath?: string
      defaultSessionTrackingModes?: ('COOKIE' | 'URL' | 'SSL')[]
      /** Format: int32 */
      effectiveMajorVersion?: number
      /** Format: int32 */
      effectiveMinorVersion?: number
      effectiveSessionTrackingModes?: ('COOKIE' | 'URL' | 'SSL')[]
      filterRegistrations?: {
        [key: string]: components['schemas']['FilterRegistration']
      }
      initParameterNames?: Record<string, never>
      jspConfigDescriptor?: components['schemas']['JspConfigDescriptor']
      /** Format: int32 */
      majorVersion?: number
      /** Format: int32 */
      minorVersion?: number
      requestCharacterEncoding?: string
      responseCharacterEncoding?: string
      serverInfo?: string
      servletContextName?: string
      servletRegistrations?: {
        [key: string]: components['schemas']['ServletRegistration']
      }
      sessionCookieConfig?: components['schemas']['SessionCookieConfig']
      /** Format: int32 */
      sessionTimeout?: number
      sessionTrackingModes?: ('COOKIE' | 'URL' | 'SSL')[]
      virtualServerName?: string
    }
    ServletRegistration: {
      className?: string
      initParameters?: {
        [key: string]: string
      }
      mappings?: string[]
      name?: string
      runAsRole?: string
    }
    SessionCookieConfig: {
      attributes?: {
        [key: string]: string
      }
      /** @deprecated */
      comment?: string
      domain?: string
      httpOnly?: boolean
      /** Format: int32 */
      maxAge?: number
      name?: string
      path?: string
      secure?: boolean
    }
    TaglibDescriptor: {
      taglibLocation?: string
      taglibURI?: string
    }
    TransactionResponse: {
      /** Format: uuid */
      accountId?: string
      /** Format: int64 */
      amountMinorUnits?: number
      currency?: string
      description?: string
      excludedFromAnalytics?: boolean
      /** Format: uuid */
      id?: string
      merchantCategory?: string
      merchantName?: string
      notes?: string
      /** Format: date-time */
      occurredAt?: string
      /** Format: date-time */
      settledAt?: string
      /** @enum {string} */
      status?: 'PENDING' | 'SETTLED'
    }
    User: {
      /** Format: date-time */
      createdAt?: string
      email?: string
      emailVerified?: boolean
      /** Format: uuid */
      id?: string
      /** Format: date-time */
      updatedAt?: string
    }
    UserResponse: {
      /** Format: date-time */
      createdAt?: string
      email?: string
      emailVerified?: boolean
      /** Format: uuid */
      id?: string
    }
    WindowSums: {
      /** Format: int64 */
      inMinorUnits?: number
      /** Format: int64 */
      outMinorUnits?: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  quickLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DevLoginRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseDevLoginResponse']
        }
      }
    }
  }
  revokeAllSessions: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseRevokeResponse']
        }
      }
    }
  }
  revokeUserSessions: {
    parameters: {
      query: {
        email: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseRevokeResponse']
        }
      }
    }
  }
  triggerBackfill: {
    parameters: {
      query: {
        userId: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  triggerIngest: {
    parameters: {
      query: {
        userId: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  resetBackfill: {
    parameters: {
      query: {
        userId: string
      }
      header?: never
      path: {
        accountId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseVoid']
        }
      }
    }
  }
  health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseHealthResponse']
        }
      }
    }
  }
  liveness: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': string
        }
      }
    }
  }
  readiness: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseReadinessResponse']
        }
      }
    }
  }
  listAccounts: {
    parameters: {
      query: {
        userId: string
        includeArchived?: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseListAccountResponse']
        }
      }
    }
  }
  getSummary: {
    parameters: {
      query: {
        userId: string
        zone?: string
      }
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseAccountSummaryResponse']
        }
      }
    }
  }
  login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseAuthResponse']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseAuthResponse']
        }
      }
    }
  }
  me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseUserResponse']
        }
      }
    }
  }
  refresh: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['RefreshRequest']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseAuthResponse']
        }
      }
    }
  }
  verify: {
    parameters: {
      query: {
        token: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseAuthResponse']
        }
      }
    }
  }
  handleCallback: {
    parameters: {
      query: {
        code?: string
        state: string
        error?: string
        error_description?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseMonzoConnectionResponse']
        }
      }
    }
  }
  initiateOAuth: {
    parameters: {
      query: {
        user: components['schemas']['User']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['RedirectView']
        }
      }
    }
  }
  initiateOAuthJson: {
    parameters: {
      query: {
        user: components['schemas']['User']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseMonzoConnectInitResponse']
        }
      }
    }
  }
  listConnections: {
    parameters: {
      query: {
        user: components['schemas']['User']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseListMonzoConnectionResponse']
        }
      }
    }
  }
  getConnection: {
    parameters: {
      query: {
        user: components['schemas']['User']
      }
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseMonzoConnectionResponse']
        }
      }
    }
  }
  disconnectConnection: {
    parameters: {
      query: {
        user: components['schemas']['User']
      }
      header?: never
      path: {
        id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getStatus: {
    parameters: {
      query: {
        user: components['schemas']['User']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseMonzoStatusResponse']
        }
      }
    }
  }
  syncNow: {
    parameters: {
      query: {
        user: components['schemas']['User']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseMonzoSyncProgressResponse']
        }
      }
    }
  }
  getSyncProgress: {
    parameters: {
      query: {
        user: components['schemas']['User']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponseMonzoSyncProgressResponse']
        }
      }
    }
  }
  list: {
    parameters: {
      query: {
        userId: string
        accountId?: string
        from?: string
        to?: string
        page?: number
        size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          '*/*': components['schemas']['ApiResponsePageResponseTransactionResponse']
        }
      }
    }
  }
}
